// navigationStepsData.ts

export interface PredefinedStepData {
  description: string;
  imageUrl?: string; // Optional: To be added later
}

export const predefinedNavigationSteps: { [key: number]: PredefinedStepData } = {
  "1": { description: "From the Library entrance, walk straight and go down the steps.", imageUrl: undefined },
  "-1": { description: "Go up the steps and walk towards the Library entrance.", imageUrl: undefined },
  "2": { description: "Walk straight toward the MLT entrance, which is on your right-hand side.", imageUrl: undefined },
  "-2": { description: "Walk towards the Library—you will see a sign labeled “Library.”", imageUrl: undefined },
  "3": { description: "Go up the steps to reach the top of the Administration Block, and continue to its entrance.", imageUrl: undefined },
  "-3": { description: "Walk straight and go down the steps to reach the MLT entrance, which is on your left.", imageUrl: undefined },
  "4": { description: "Go down the steps to reach the Library entrance at the bottom.", imageUrl: undefined },
  "-4": { description: "To the left of the Library, go up the steps toward the Car exit gate.", imageUrl: undefined },
  "5": { description: "From the Car exit gate, walk straight until you see a corridor on your right leading to MLT.", imageUrl: undefined },
  "-5": { description: "Walk straight toward the Car exit gate.", imageUrl: undefined },
  "6": { description: "Walk straight and go down the steps toward the MLT building, then turn left or right if you don’t want to enter MLT.", imageUrl: undefined },
  "-6": { description: "Go up the steps and continue walking forward.", imageUrl: undefined },
  "7": { description: "Walk straight from the Car exit gate, turn right to reach the Administration Block.", imageUrl: undefined },
  "-7": { description: "Walk straight toward the Car exit gate.", imageUrl: undefined },
  "8": { description: "Walk toward the Administration Block entrance.", imageUrl: undefined },
  "-8": { description: "Walk toward the Main entry gate.", imageUrl: undefined },
  "9": { description: "Walk from the ODL Entrance Gate to the main entry gate.", imageUrl: "https://ik.imagekit.io/ecz9rj5wg/try.jpg?updatedAt=1751399149479" },
  "-9": { description: "Enter through the Main entry gate.", imageUrl: undefined },
  "10": { description: "Walk straight and turn right to reach the Administration entrance.", imageUrl: undefined },
  "-10": { description: "Walk straight toward the Main entry gate.", imageUrl: undefined },
  "11": { description: "Turn right and walk until you see steps going down on your right.", imageUrl: undefined },
  "-11": { description: "Walk straight toward the Car Entrance Gate.", imageUrl: undefined },
  "12": { description: "Walk toward the Car Entrance Gate.", imageUrl: undefined },
  "-12": { description: "Enter through the Car Entrance Gate and walk straight.", imageUrl: undefined },
  "13": { description: "After entering the Car Entrance Gate, turn left and walk until you see steps going down on your right.", imageUrl: undefined },
  "-13": { description: "Walk straight toward the Car Entrance Gate.", imageUrl: undefined },
  "14": { description: "Go down the steps and continue walking forward.", imageUrl: undefined },
  "-14": { description: "Walk straight and go up the steps to the top.", imageUrl: undefined },
  "15": { description: "Walk straight.", imageUrl: undefined },
  "-15": { description: "Walk straight toward the Butterfly, which is on your left.", imageUrl: undefined },
  "16": { description: "From the Butterfly corridor, walk straight into the Main Building corridor.", imageUrl: undefined },
  "-16": { description: "Walk straight from the Main Building corridor into the Butterfly corridor.", imageUrl: undefined },
  "17": { description: "Walk straight behind the Main Building.", imageUrl: undefined },
  "-17": { description: "Walk behind the Main Building, and in front, you will see steps and the Clinic on your left.", imageUrl: undefined },
  "18": { description: "Go up the steps on your right.", imageUrl: undefined },
  "-18": { description: "Go down the steps.", imageUrl: undefined },
  "19": { description: "Walk straight until you reach the corridor with the Clinic.", imageUrl: undefined },
  "-19": { description: "Walk straight behind the Main Building.", imageUrl: undefined },
  "20": { description: "Walk straight in the corridor toward the Engineering Building.", imageUrl: undefined },
  "-20": { description: "Walk straight in the corridor toward the end of the corridor.", imageUrl: undefined },
  "21": { description: "Walk straight behind the Administration Block door.", imageUrl: undefined },
  "-21": { description: "Walk straight behind the Administration Building.", imageUrl: undefined },
  "22": { description: "From the back of the Administration Block door, walk forward.", imageUrl: undefined },
  "-22": { description: "Walk toward the back of the Administration Block door.", imageUrl: undefined },
  "23": { description: "From behind the Administration Block door, continue walking forward.", imageUrl: undefined },
  "-23": { description: "Walk toward the back door of the Administration Block.", imageUrl: undefined },
  "24": { description: "Walk straight in the corridor behind the MLT building.", imageUrl: undefined },
  "-24": { description: "Walk straight in the corridor behind the MLT building toward the Electrical Building.", imageUrl: undefined },
  "25": { description: "Walk straight in the corridor—you're nearly at OT.", imageUrl: undefined },
  "-25": { description: "Walk in the corridor toward MLT, located on the left side of the corridor.", imageUrl: undefined },
  "26": { description: "Continue to the end of the corridor.", imageUrl: undefined },
  "-26": { description: "Walk straight in the corridor located to the right of the Library.", imageUrl: undefined },
  "27": { description: "Enter through the Behind library gate, then turn right to reach the corridor.", imageUrl: undefined },
  "-27": { description: "From the corridor, turn right, then left to reach the gate.", imageUrl: undefined },
  "28": { description: "Walk straight to reach the Café.", imageUrl: undefined },
  "-28": { description: "Walk from the Café back to the corridor.", imageUrl: undefined },
  "29": { description: "To the right of the Library, walk forward in the corridor toward OT.", imageUrl: undefined },
  "-29": { description: "Walk forward toward the Library.", imageUrl: undefined },
  "30": { description: "Enter OT.", imageUrl: undefined },
  "-30": { description: "Exit OT.", imageUrl: undefined },
  "31": { description: "Walk from the Café side toward the back of the Wet Building.", imageUrl: undefined },
  "-31": { description: "Walk from behind the Wet Building toward the Café side.", imageUrl: undefined },
  "32": { description: "Walk toward the back door of the Wet Building.", imageUrl: undefined },
  "-32": { description: "Walk from the back door of the Wet Building into the corridor.", imageUrl: undefined },
  "33": { description: "Walk toward the Mini Shop.", imageUrl: undefined },
  "-33": { description: "Walk toward the corridor.", imageUrl: undefined },
  "34": { description: "Enter through the Mini shop gate.", imageUrl: undefined },
  "-34": { description: "Walk toward the Mini shop gate.", imageUrl: undefined },
  "35": { description: "Walk through the corridor on the left of the Electrical Building.", imageUrl: undefined },
  "-35": { description: "Walk through the corridor toward the Electrical Building.", imageUrl: undefined },
  "36": { description: "Exit the Wet Building.", imageUrl: undefined },
  "-36": { description: "Walk toward the entrance of the Wet Building.", imageUrl: undefined },
  "37": { description: "Walk toward T7 (Civil Engineering).", imageUrl: undefined },
  "-37": { description: "Walk into the left-side corridor of T7.", imageUrl: undefined },
  "38": { description: "Walk close to the Wet Building.", imageUrl: undefined },
  "-38": { description: "Walk toward the Electrical Building corridor.", imageUrl: undefined },
  "39": { description: "Walk into the corridor where you pass Dosa and Dean Offices on your left inside MLT.", imageUrl: undefined },
  "-39": { description: "Walk into the corridor where you pass Dosa and Dean Offices on your right inside MLT.", imageUrl: undefined },
  "40": { description: "Walk toward the Mechanical Fitting and Welding Workshop (T3) and Machine Shop (T4).", imageUrl: undefined },
  "-40": { description: "Walk toward the T7 (Civil Engineering) corridor.", imageUrl: undefined },
  "41": { description: "Go up the steps toward the Mechanical Engineering Labs (T1 & T2).", imageUrl: undefined },
  "-41": { description: "Go down the steps toward T3 and T4 (Workshops).", imageUrl: undefined },
  "42": { description: "Walk from the Main Building toward the Engineering Building entrance.", imageUrl: undefined },
  "-42": { description: "Walk from the Engineering Building toward the Main Building.", imageUrl: undefined },
  "43": { description: "Enter through the gate between the Education Department Office and the Engineering Building.", imageUrl: undefined },
  "-43": { description: "Exit through the gate between the Education Department Office and the Engineering Building.", imageUrl: undefined },
  "44": { description: "Enter through the Education Department entrance.", imageUrl: undefined },
  "-44": { description: "Exit through the Education Department entrance.", imageUrl: undefined },
  "45": { description: "Walk from the Mini Shop to the junction (4-way).", imageUrl: undefined },
  "-45": { description: "Walk from the junction toward the Mini Shop.", imageUrl: undefined },
  "46": { description: "Walk toward the steps going down.", imageUrl: undefined },
  "-46": { description: "Walk toward the Wet Building.", imageUrl: undefined },
  "47": { description: "Walk forward behind T7.", imageUrl: undefined },
  "-47": { description: "Walk toward the junction (4-way).", imageUrl: undefined },
  "48": { description: "Walk toward the Hostels.", imageUrl: undefined },
  "-48": { description: "Walk toward the road.", imageUrl: undefined },
  "49": { description: "Walk forward along the road.", imageUrl: undefined },
  "-49": { description: "Walk forward along the road.", imageUrl: undefined },
  "50": { description: "Walk toward Mpingwi Hostel.", imageUrl: undefined },
  "-50": { description: "Walk toward the road.", imageUrl: undefined },
  "51": { description: "Walk toward the Gate near T8.", imageUrl: undefined },
  "-51": { description: "Walk forward along the road.", imageUrl: undefined },
  "52": { description: "Enter through the gate.", imageUrl: undefined },
  "-52": { description: "Exit through the gate.", imageUrl: undefined },
  "53": { description: "Exit through the NT Gate.", imageUrl: undefined },
  "-53": { description: "Enter through the NT Gate.", imageUrl: undefined },
  "54": { description: "Exit through the gate behind the Engineering Building.", imageUrl: undefined },
  "-54": { description: "Enter through the gate behind the Engineering Building.", imageUrl: undefined },
  "55": { description: "Walk toward Nyika A Hostel.", imageUrl: undefined },
  "-55": { description: "Walk toward Mpingwi Hostel.", imageUrl: undefined },
  "56": { description: "Walk toward Ndirande A Hostel.", imageUrl: undefined },
  "-56": { description: "Walk toward the road.", imageUrl: undefined },
  "57": { description: "Walk into the corridor where the Electrical Building is on your right.", imageUrl: undefined },
  "-57": { description: "Walk into the corridor where the Electrical Building is on your left.", imageUrl: undefined },
  "58": { description: "Walk toward Kapeni A Hostel.", imageUrl: undefined },
  "-58": { description: "Walk toward the corridor.", imageUrl: undefined },
  "59": { description: "Walk toward Ndirande B Hostel.", imageUrl: undefined },
  "-59": { description: "Walk toward the corridor.", imageUrl: undefined },
  "60": { description: "Walk toward Kapeni B Hostel.", imageUrl: undefined },
  "-60": { description: "Walk toward the corridor.", imageUrl: undefined },
  "61": { description: "Walk straight and turn left to reach the Tuck shop.", imageUrl: undefined },
  "-61": { description: "Walk straight and turn right to reach Mpingwi, which is on your left.", imageUrl: undefined },
  "62": { description: "Walk straight and turn right to reach the Tuck shop.", imageUrl: undefined },
  "-62": { description: "Walk and turn left to reach T8, which is on your right.", imageUrl: undefined },
  "63": { description: "Walk straight to reach the Main Lecture Theatre entrance, which is on the left.", imageUrl: undefined },
  "-63": { description: "Walk straight to reach the Library.", imageUrl: undefined },
  "64": { description: "Walk straight to reach the Administration Block entrance on the left.", imageUrl: undefined },
  "-64": { description: "Walk straight to reach the Library.", imageUrl: undefined },
  "65": { description: "Walk straight and turn right to reach the Administration Block.", imageUrl: undefined },
  "-65": { description: "Walk straight and turn left to reach the Car exit gate.", imageUrl: undefined },
  "66": { description: "Walk straight and turn left to reach the Administration Block.", imageUrl: undefined },
  "-66": { description: "Walk straight and turn right to reach the Car Entrance Gate.", imageUrl: undefined },
  "67": { description: "Walk straight and turn right to reach the Main Lecture Theatre.", imageUrl: undefined },
  "-67": { description: "Walk straight and turn left to reach the Car exit gate.", imageUrl: undefined },
  "68": { description: "Walk straight and turn left to reach the Main Lecture Theatre.", imageUrl: undefined },
  "-68": { description: "Walk straight and turn right to reach the Car Entrance Gate.", imageUrl: undefined },
  "69": { description: "Walk straight from the Car exit gate to reach the Car Entrance Gate.", imageUrl: undefined },
  "-69": { description: "Walk straight from the Car Entrance Gate to reach the Car exit gate.", imageUrl: undefined },
  "70": { description: "Walk straight from the Car exit gate to reach the Main entry gate on the left side.", imageUrl: undefined },
  "-70": { description: "Walk straight from the Main entry gate to reach the Car exit gate.", imageUrl: undefined },
  "71": { description: "Walk straight from the Car Entrance Gate to reach the Main entry gate on the right side.", imageUrl: undefined },
  "-71": { description: "Walk straight from the Main entry gate to reach the Car Entrance Gate.", imageUrl: undefined },
  "72": { description: "Walk straight from the Car Entrance Gate to reach the Engineering gate.", imageUrl: undefined },
  "-72": { description: "Walk straight from the Engineering gate to reach the Car Entrance Gate.", imageUrl: undefined },
  "73": { description: "Walk straight from the Car Entrance Gate to reach the behind Engineering Building gate.", imageUrl: undefined },
  "-73": { description: "Walk straight from the behind Engineering Building gate to reach the Car Entrance Gate.", imageUrl: undefined },
  "74": { description: "Walk straight from the Car Entrance Gate to reach the T8 Gate.", imageUrl: undefined },
  "-74": { description: "Walk straight from the T8 Gate to reach the Car Entrance Gate.", imageUrl: undefined },
  "75": { description: "Walk straight from the Car Entrance Gate to reach the NT Gate.", imageUrl: undefined },
  "-75": { description: "Walk straight from the NT Gate to reach the Car Entrance Gate.", imageUrl: undefined },
  "76": { description: "Walk straight from the Engineering gate to reach the behind Engineering Building gate.", imageUrl: undefined },
  "-76": { description: "Walk straight from the behind Engineering Building gate to reach the Engineering gate.", imageUrl: undefined },
  "77": { description: "Walk straight from the Engineering gate to reach the T8 Gate.", imageUrl: undefined },
  "-77": { description: "Walk straight from the T8 Gate to reach the Engineering gate.", imageUrl: undefined },
  "78": { description: "Walk straight from the Engineering gate to reach the NT Gate.", imageUrl: undefined },
  "-78": { description: "Walk straight from the NT Gate to reach the Engineering gate.", imageUrl: undefined },
  "79": { description: "Walk straight from the T8 Gate to reach the NT Gate.", imageUrl: undefined },
  "-79": { description: "Walk straight from the NT Gate to reach the T8 Gate.", imageUrl: undefined },
  "80": { description: "Walk straight from the behind Engineering Building gate to reach the T8 Gate.", imageUrl: undefined },
  "-80": { description: "Walk straight from the T8 Gate to reach the behind Engineering Building gate.", imageUrl: undefined },
  "81": { description: "Walk straight from the behind Engineering Building gate to reach the NT Gate.", imageUrl: undefined },
  "-81": { description: "Walk straight from the NT Gate to reach the behind Engineering Building gate.", imageUrl: undefined },
  "82": { description: "Walk down the steps and turn left.", imageUrl: undefined },
  "-82": { description: "Walk straight and turn right, then go up the steps.", imageUrl: undefined },
  "83": { description: "Walk down the steps, then turn left and right.", imageUrl: undefined },
  "-83": { description: "Walk straight, then turn left and right, then go up the steps.", imageUrl: undefined },
  "84": { description: "Walk straight, turn left and then left again, to enter the Main Building.", imageUrl: undefined },
  "-84": { description: "Walk straight, turn right and then left, and continue straight.", imageUrl: undefined },
  "85": { description: "Walk straight and turn right.", imageUrl: undefined },
  "-85": { description: "Walk straight and turn left.", imageUrl: undefined },
  "86": { description: "Walk straight, then turn left, then left again, and then right to reach the Butterfly.", imageUrl: undefined },
  "-86": { description: "Walk straight, then turn left and right, then right again.", imageUrl: undefined },
  "87": { description: "Walk straight, turn left and right, then continue straight.", imageUrl: undefined },
  "-87": { description: "Walk straight, turn left and right, then move straight to reach the Butterfly.", imageUrl: undefined },
  "88": { description: "Walk to the left of the Electrical Building, turn left, move through that corridor, then turn right near the Wet Building.", imageUrl: undefined },
  "-88": { description: "Walk straight, turn left, continue in that corridor, then turn right at the end.", imageUrl: undefined },
  "89": { description: "Walk straight to the left corridor of the Café, turn right, then turn left to reach the Library.", imageUrl: undefined },
  "-89": { description: "Walk straight to the left corridor of the Library, turn right, then turn left to reach the Café.", imageUrl: undefined },
  "90": { description: "Walk straight to reach the road near the Mini Shop.", imageUrl: undefined },
  "-90": { description: "Walk straight in the corridor toward the Café.", imageUrl: undefined },
  "91": { description: "Walk straight from the Mini shop gate toward the T8 Gate.", imageUrl: undefined },
  "-91": { description: "Walk straight from the T8 Gate toward the Mini shop gate.", imageUrl: undefined },
  "92": { description: "Walk through the left corridor of the Electrical Building toward the Wet Building.", imageUrl: undefined },
  "-92": { description: "Walk through the corridor toward the Electrical Building.", imageUrl: undefined },
  "93": { description: "Walk through this corridor toward the down steps to reach the road.", imageUrl: undefined },
  "-93": { description: "Walk up the steps, then continue through the corridor.", imageUrl: undefined },
  "94": { description: "Walk through the corridor beside the Open Theatre toward the Electrical Building.", imageUrl: undefined },
  "-94": { description: "Walk through the corridor toward the Open Theatre.", imageUrl: undefined },
  "95": { description: "Walk toward Nyika A Hostel.", imageUrl: undefined },
  "-95": { description: "Walk toward the road.", imageUrl: undefined },
  "96": { description: "Walk toward Nyika B Hostel.", imageUrl: undefined },
  "-96": { description: "Walk toward the road.", imageUrl: undefined },
  "97": { description: "Walk forward along the road.", imageUrl: undefined },
  "-97": { description: "Walk forward along the road.", imageUrl: undefined },
  "98": { description: "Walk through the corridor toward the Mechanical Workshops (T3 & T4).", imageUrl: undefined },
  "-98": { description: "Walk through the corridor to reach T7 (Civil Engineering).", imageUrl: undefined },
  "99": { description: "Walk straight toward the T8 Gate.", imageUrl: undefined },
  "-99": { description: "Walk down the road.", imageUrl: undefined },
  "100": { description: "Walk through this corridor.", imageUrl: undefined },
  "-100": { description: "Walk through this corridor.", imageUrl: undefined },
  "101": { description: "Exit through the door behind the Engineering Building.", imageUrl: undefined },
  "-101": { description: "Enter through the door behind the Engineering Building.", imageUrl: undefined },
  "102": { description: "Walk inside the Wet Building and go down the steps.", imageUrl: undefined },
  "-102": { description: "Enter through the back door of the Wet Building and go up the steps.", imageUrl: undefined },
  "104": { description: "Walk straight and turn to the right to take up steps to reach corridor new clinic", imageUrl: undefined },
  "-104": { description: "Walk down steps and turn right", imageUrl: undefined },
  "110": { description: "Turn left again", imageUrl: undefined },
  "111": { description: "To your left, you’ll find Room 302.", imageUrl: undefined },
  "112": { description: "To your left, you’ll find Room 303", imageUrl: undefined },
  "113": { description: "Turn right.", imageUrl: undefined },
  "114": { description: "Look to your right-hand side until you see Room 204 (ICT Office).", imageUrl: undefined },
  "115": { description: "Look to your right-hand side within this corridor to find Room 304", imageUrl: undefined },
  "116": { description: "On this corridor, you will find Room 307 on the left-hand side.", imageUrl: undefined },
  "117": { description: "On this corridor, you will find Room 308 on the right-hand side", imageUrl: undefined },
  "118": { description: "On your left-hand side, you’ll find Room 404.", imageUrl: undefined },
  "119": { description: "On your right-hand side, you’ll find Room 402 (ICT Support Office).", imageUrl: undefined },
  "120": { description: "On this corridor, Room 408 will be on the left-hand side.", imageUrl: undefined },
  "121": { description: "You will find room B2.35", imageUrl: undefined },
  "122": { description: "You will find room B2.34", imageUrl: undefined },
  "123": { description: "You will find room B2.33", imageUrl: undefined },
  "124": { description: "You will find room B2.32", imageUrl: undefined },
  "125": { description: "You will find room B2.31", imageUrl: undefined },
  "126": { description: "You will find room B2.36", imageUrl: undefined },
  "127": { description: "You will find room B2.37", imageUrl: undefined },
  "128": { description: "You will find room B2.38", imageUrl: undefined },
  "129": { description: "You will find room B2.39", imageUrl: undefined },
  "130": { description: "You will find room B2.40", imageUrl: undefined },
  "131": { description: "To your right side, you will find room B3.44", imageUrl: undefined },
  "132": { description: "To your right side, you will find room B3.42", imageUrl: undefined },
  "133": { description: "To your right side, you will find room B3.40", imageUrl: undefined },
  "134": { description: "To your right side, you will find room B3.38", imageUrl: undefined },
  "135": { description: "To your right side, you will find room B3.36", imageUrl: undefined },
  "136": { description: "To your right side, you will find room B3.34", imageUrl: undefined },
  "137": { description: "To your right side, you will find room B3.32", imageUrl: undefined },
  "138": { description: "To your left side, you will find room B3.43", imageUrl: undefined },
  "139": { description: "To your left side, you will find room B3.41", imageUrl: undefined },
  "140": { description: "To your left side, you will find room B3.39", imageUrl: undefined },
  "141": { description: "To your left side, you will find room B3.35", imageUrl: undefined },
  "142": { description: "To your left side, you will find room B3.33", imageUrl: undefined },
  "143": { description: "To your left side, you will find room B3.31", imageUrl: undefined },
  "144": { description: "To your left side, you will find room B3.48", imageUrl: undefined },
  "145": { description: "To your left side, you will find room B3.50", imageUrl: undefined },
  "146": { description: "To your left side, you will find room B3.52", imageUrl: undefined },
  "147": { description: "To your left side, you will find room B3.54", imageUrl: undefined },
  "148": { description: "To your left side, you will find room B3.56", imageUrl: undefined },
  "149": { description: "To your right side, you will find room B3.46", imageUrl: undefined },
  "150": { description: "To your right side, you will find room B3.47", imageUrl: undefined },
  "151": { description: "To your right side, you will find room B3.49", imageUrl: undefined },
  "152": { description: "To your right side, you will find room B3.51", imageUrl: undefined },
  "153": { description: "To your right side, you will find room B3.53", imageUrl: undefined },
  "154": { description: "To your right side, you will find room B3.55", imageUrl: undefined },
  "155": { description: "To your right side, you will find room B4.46", imageUrl: undefined },
  "156": { description: "To your right side, you will find room B4.47", imageUrl: undefined },
  "157": { description: "To your right side, you will find room B4.49", imageUrl: undefined },
  "158": { description: "To your right side, you will find room B4.51", imageUrl: undefined },
  "159": { description: "To your right side, you will find room B4.53", imageUrl: undefined },
  "160": { description: "To your right side, you will find room B4.55", imageUrl: undefined },
  "161": { description: "To your left side, you will find room B4.48", imageUrl: undefined },
  "162": { description: "To your left side, you will find room B4.50", imageUrl: undefined },
  "163": { description: "To your left side, you will find room B4.52", imageUrl: undefined },
  "164": { description: "To your left side, you will find room B4.54", imageUrl: undefined },
  "165": { description: "To your left side, you will find room B4.56", imageUrl: undefined },
  "166": { description: "To your right side, you will find room B4.44", imageUrl: undefined },
  "167": { description: "To your right side, you will find room B4.42", imageUrl: undefined },
  "168": { description: "To your right side, you will find room B4.40", imageUrl: undefined },
  "169": { description: "To your right side, you will find room B4.38", imageUrl: undefined },
  "170": { description: "To your right side, you will find room B4.36", imageUrl: undefined },
  "171": { description: "To your right side, you will find room B4.34", imageUrl: undefined },
  "172": { description: "To your right side, you will find room B4.32", imageUrl: undefined },
  "173": { description: "To your left side, you will find room B4.43", imageUrl: undefined },
  "174": { description: "To your left side, you will find room B4.41", imageUrl: undefined },
  "175": { description: "To your left side, you will find room B4.39", imageUrl: undefined },
  "176": { description: "To your left side, you will find room B4.37", imageUrl: undefined },
  "177": { description: "To your left side, you will find room B4.35", imageUrl: undefined },
  "178": { description: "To your left side, you will find room B4.33", imageUrl: undefined },
  "179": { description: "To your left side, you will find room B4.31", imageUrl: undefined },
  "180": { description: "To your left side, you will find B1.05", imageUrl: undefined },
  "181": { description: "To your left side, you will find B1.04", imageUrl: undefined },
  "182": { description: "To your left side, you will find B1.03", imageUrl: undefined },
  "183": { description: "To your left side, you will find B1.02", imageUrl: undefined },
  "184": { description: "To your left side, you will find B1.01", imageUrl: undefined },
  "185": { description: "To your right side, you will find B1.07", imageUrl: undefined },
  "186": { description: "To your right side, you will find B1.08", imageUrl: undefined },
  "187": { description: "To your right side, you will find B1.09", imageUrl: undefined },
  "188": { description: "To your right side, you will find B1.10", imageUrl: undefined },
  "189": { description: "To your right side, you will find B1.12", imageUrl: undefined },
  "190": { description: "To your right side, you will find B2.09", imageUrl: undefined },
  "191": { description: "To your right side, you will find B2.07", imageUrl: undefined },
  "192": { description: "To your right side, you will find B2.05", imageUrl: undefined },
  "193": { description: "To your right side, you will find B2.03", imageUrl: undefined },
  "194": { description: "To your right side, you will find B2.02", imageUrl: undefined },
  "195": { description: "To your left side, you will find B2.10", imageUrl: undefined },
  "196": { description: "To your left side, you will find B2.08", imageUrl: undefined },
  "197": { description: "To your left side, you will find B2.06", imageUrl: undefined },
  "198": { description: "To your left side, you will find B2.04", imageUrl: undefined },
  "199": { description: "To your left side, you will find B2.01", imageUrl: undefined },
  "200": { description: "To your right side, you will find B2.14", imageUrl: undefined },
  "201": { description: "To your right side, you will find B2.16", imageUrl: undefined },
  "202": { description: "To your right side, you will find B2.18", imageUrl: undefined },
  "203": { description: "To your right side, you will find B2.20", imageUrl: undefined },
  "204": { description: "To your right side, you will find B2.22", imageUrl: undefined },
  "205": { description: "To your right side, you will find B2.24", imageUrl: undefined },
  "206": { description: "To your right side, you will find B2.26", imageUrl: undefined },
  "207": { description: "To your left side, you will find B2.12", imageUrl: undefined },
  "208": { description: "To your left side, you will find B2.13", imageUrl: undefined },
  "209": { description: "To your left side, you will find B2.15", imageUrl: undefined },
  "210": { description: "To your left side, you will find B2.17", imageUrl: undefined },
  "211": { description: "To your left side, you will find B2.19", imageUrl: undefined },
  "212": { description: "To your left side, you will find B2.21", imageUrl: undefined },
  "213": { description: "To your left side, you will find B2.23", imageUrl: undefined },
  "214": { description: "To your left side, you will find B2.25", imageUrl: undefined },
  "215": { description: "To your left side, you will find B3.12", imageUrl: undefined },
  "216": { description: "To your left side, you will find B3.14", imageUrl: undefined },
  "217": { description: "To your left side, you will find B3.16", imageUrl: undefined },
  "218": { description: "To your left side, you will find B3.18", imageUrl: undefined },
  "219": { description: "To your left side, you will find B3.20", imageUrl: undefined },
  "220": { description: "To your left side, you will find B3.22", imageUrl: undefined },
  "221": { description: "To your left side, you will find B3.24", imageUrl: undefined },
  "222": { description: "To your left side, you will find B3.26", imageUrl: undefined },
  "223": { description: "To your right side, you will find B3.13", imageUrl: undefined },
  "224": { description: "To your right side, you will find B3.15", imageUrl: undefined },
  "225": { description: "To your right side, you will find B3.17", imageUrl: undefined },
  "226": { description: "To your right side, you will find B3.19", imageUrl: undefined },
  "227": { description: "To your right side, you will find B3.21", imageUrl: undefined },
  "228": { description: "To your right side, you will find B3.23", imageUrl: undefined },
  "229": { description: "To your right side, you will find B3.25", imageUrl: undefined },
  "230": { description: "To your right side, you will find B3.09", imageUrl: undefined },
  "231": { description: "To your right side, you will find B3.07", imageUrl: undefined },
  "232": { description: "To your right side, you will find B3.05", imageUrl: undefined },
  "233": { description: "To your right side, you will find B3.03", imageUrl: undefined },
  "234": { description: "To your right side, you will find B3.01", imageUrl: undefined },
  "235": { description: "To your left side, you will find B3.10", imageUrl: undefined },
  "236": { description: "To your left side, you will find B3.08", imageUrl: undefined },
  "237": { description: "To your left side, you will find B3.06", imageUrl: undefined },
  "238": { description: "To your left side, you will find B3.04", imageUrl: undefined },
  "239": { description: "To your left side, you will find B3.02", imageUrl: undefined },
  "240": { description: "You will find room 2.35", imageUrl: undefined },
  "241": { description: "You will find room 2.34", imageUrl: undefined },
  "242": { description: "You will find room 2.33", imageUrl: undefined },
  "243": { description: "You will find room 2.32", imageUrl: undefined },
  "244": { description: "You will find room 2.31", imageUrl: undefined },
  "245": { description: "You will find room 2.36", imageUrl: undefined },
  "246": { description: "You will find room 2.37", imageUrl: undefined },
  "247": { description: "You will find room 2.38", imageUrl: undefined },
  "248": { description: "You will find room 2.39", imageUrl: undefined },
  "249": { description: "To your right side, you will find room 3.44", imageUrl: undefined },
  "250": { description: "To your right side, you will find room 3.42", imageUrl: undefined },
  "251": { description: "To your right side, you will find room 3.40", imageUrl: undefined },
  "252": { description: "To your right side, you will find room 3.38", imageUrl: undefined },
  "253": { description: "To your right side, you will find room 3.36", imageUrl: undefined },
  "254": { description: "To your right side, you will find room 3.34", imageUrl: undefined },
  "255": { description: "To your right side, you will find room 3.32", imageUrl: undefined },
  "256": { description: "To your left side, you will find room 3.43", imageUrl: undefined },
  "257": { description: "To your left side, you will find room 3.41", imageUrl: undefined },
  "258": { description: "To your left side, you will find room 3.39", imageUrl: undefined },
  "259": { description: "To your left side, you will find room 3.27", imageUrl: undefined },
  "260": { description: "To your left side, you will find room 3.35", imageUrl: undefined },
  "261": { description: "To your left side, you will find room 3.33", imageUrl: undefined },
  "262": { description: "To your left side, you will find room 3.31", imageUrl: undefined },
  "263": { description: "To your right side, you will find room 3.46", imageUrl: undefined },
  "264": { description: "To your right side, you will find room 3.47", imageUrl: undefined },
  "265": { description: "To your right side, you will find room 3.49", imageUrl: undefined },
  "266": { description: "To your right side, you will find room 3.51", imageUrl: undefined },
  "267": { description: "To your right side, you will find room 3.53", imageUrl: undefined },
  "268": { description: "To your right side, you will find room 3.55", imageUrl: undefined },
  "269": { description: "To your left side, you will find room 3.48", imageUrl: undefined },
  "270": { description: "To your left side, you will find room 3.50", imageUrl: undefined },
  "271": { description: "To your left side, you will find room 3.52", imageUrl: undefined },
  "272": { description: "To your left side, you will find room 3.54", imageUrl: undefined },
  "273": { description: "To your left side, you will find room 3.56", imageUrl: undefined },
  "274": { description: "To your left side, you will find room 4.48", imageUrl: undefined },
  "275": { description: "To your left side, you will find room 4.50", imageUrl: undefined },
  "276": { description: "To your left side, you will find room 4.52", imageUrl: undefined },
  "277": { description: "To your left side, you will find room 4.54", imageUrl: undefined },
  "278": { description: "To your left side, you will find room 4.56", imageUrl: undefined },
  "279": { description: "To your right side, you will find room 4.46", imageUrl: undefined },
  "280": { description: "To your right side, you will find room 4.47", imageUrl: undefined },
  "281": { description: "To your right side, you will find room 4.49", imageUrl: undefined },
  "282": { description: "To your right side, you will find room 4.51", imageUrl: undefined },
  "283": { description: "To your right side, you will find room 4.53", imageUrl: undefined },
  "284": { description: "To your right side, you will find room 4.55", imageUrl: undefined },
  "285": { description: "To your right side, you will find room 4.44", imageUrl: undefined },
  "286": { description: "To your right side, you will find room 4.42", imageUrl: undefined },
  "287": { description: "To your right side, you will find room 4.40", imageUrl: undefined },
  "288": { description: "To your right side, you will find room 4.38", imageUrl: undefined },
  "289": { description: "To your right side, you will find room 4.36", imageUrl: undefined },
  "290": { description: "To your right side, you will find room 4.34", imageUrl: undefined },
  "291": { description: "To your right side, you will find room 4.32", imageUrl: undefined },
  "292": { description: "To your left side, you will find room 4.43", imageUrl: undefined },
  "293": { description: "To your left side, you will find room 4.41", imageUrl: undefined },
  "294": { description: "To your left side, you will find room 4.39", imageUrl: undefined },
  "295": { description: "To your left side, you will find room 4.37", imageUrl: undefined },
  "296": { description: "To your left side, you will find room 4.35", imageUrl: undefined },
  "297": { description: "To your left side, you will find room 4.33", imageUrl: undefined },
  "298": { description: "To your left side, you will find room 4.31", imageUrl: undefined },
  "299": { description: "To your left side, you will find room 2.25", imageUrl: undefined },
  "300": { description: "To your left side, you will find room 2.23", imageUrl: undefined },
  "301": { description: "To your left side, you will find room 2.21", imageUrl: undefined },
  "302": { description: "To your left side, you will find room 2.19", imageUrl: undefined },
  "303": { description: "To your left side, you will find room 2.17", imageUrl: undefined },
  "304": { description: "To your left side, you will find room 2.15", imageUrl: undefined },
  "305": { description: "To your left side, you will find room 2.13", imageUrl: undefined },
  "306": { description: "To your left side, you will find room 2.09", imageUrl: undefined },
  "307": { description: "To your left side, you will find room 2.07", imageUrl: undefined },
  "308": { description: "To your left side, you will find room 2.05", imageUrl: undefined },
  "309": { description: "To your left side, you will find room 2.03", imageUrl: undefined },
  "310": { description: "To your left side, you will find room 2.01", imageUrl: undefined },
  "311": { description: "To your right side, you will find room 2.26", imageUrl: undefined },
  "312": { description: "To your right side, you will find room 2.24", imageUrl: undefined },
  "313": { description: "To your right side, you will find room 2.22", imageUrl: undefined },
  "314": { description: "To your right side, you will find room 2.20", imageUrl: undefined },
  "315": { description: "To your right side, you will find room 2.18", imageUrl: undefined },
  "316": { description: "To your right side, you will find room 2.16", imageUrl: undefined },
  "317": { description: "To your right side, you will find room 2.14", imageUrl: undefined },
  "318": { description: "To your right side, you will find room 2.12", imageUrl: undefined },
  "319": { description: "To your right side, you will find room 2.11", imageUrl: undefined },
  "320": { description: "To your right side, you will find room 2.10", imageUrl: undefined },
  "321": { description: "To your right side, you will find room 2.08", imageUrl: undefined },
  "322": { description: "To your right side, you will find room 2.06", imageUrl: undefined },
  "323": { description: "To your right side, you will find room 2.04", imageUrl: undefined },
  "324": { description: "To your right side, you will find room 2.02", imageUrl: undefined },
  "325": { description: "To your left side, you will find room 3.25", imageUrl: undefined },
  "326": { description: "To your left side, you will find room 3.23", imageUrl: undefined },
  "327": { description: "To your left side, you will find room 3.21", imageUrl: undefined },
  "328": { description: "To your left side, you will find room 3.19", imageUrl: undefined },
  "329": { description: "To your left side, you will find room 3.17", imageUrl: undefined },
  "330": { description: "To your left side, you will find room 3.15", imageUrl: undefined },
  "331": { description: "To your left side, you will find room 3.13", imageUrl: undefined },
  "332": { description: "To your left side, you will find room 3.09", imageUrl: undefined },
  "333": { description: "To your left side, you will find room 3.07", imageUrl: undefined },
  "334": { description: "To your left side, you will find room 3.05", imageUrl: undefined },
  "335": { description: "To your left side, you will find room 3.03", imageUrl: undefined },
  "336": { description: "To your left side, you will find room 3.01", imageUrl: undefined },
  "337": { description: "To your right side, you will find room 3.26", imageUrl: undefined },
  "338": { description: "To your right side, you will find room 3.24", imageUrl: undefined },
  "339": { description: "To your right side, you will find room 3.22", imageUrl: undefined },
  "340": { description: "To your right side, you will find room 3.20", imageUrl: undefined },
  "341": { description: "To your right side, you will find room 3.18", imageUrl: undefined },
  "342": { description: "To your right side, you will find room 3.16", imageUrl: undefined },
  "343": { description: "To your right side, you will find room 3.14", imageUrl: undefined },
  "344": { description: "To your right side, you will find room 3.12", imageUrl: undefined },
  "345": { description: "To your right side, you will find room 3.11", imageUrl: undefined },
  "346": { description: "To your right side, you will find room 3.10", imageUrl: undefined },
  "347": { description: "To your right side, you will find room 3.08", imageUrl: undefined },
  "348": { description: "To your right side, you will find room 3.06", imageUrl: undefined },
  "349": { description: "To your right side, you will find room 3.04", imageUrl: undefined },
  "350": { description: "To your right side, you will find room 3.02", imageUrl: undefined },
  "351": { description: "You will find room A2.35", imageUrl: undefined },
  "352": { description: "You will find room A2.34", imageUrl: undefined },
  "353": { description: "You will find room A2.33", imageUrl: undefined },
  "354": { description: "You will find room A2.32", imageUrl: undefined },
  "355": { description: "You will find room A2.31", imageUrl: undefined },
  "356": { description: "You will find room A2.36", imageUrl: undefined },
  "357": { description: "You will find room A2.37", imageUrl: undefined },
  "358": { description: "You will find room A2.38", imageUrl: undefined },
  "359": { description: "You will find room A2.39", imageUrl: undefined },
  "360": { description: "You will find room A2.40", imageUrl: undefined },
  "361": { description: "To your right side, you will find room A3.41", imageUrl: undefined },
  "362": { description: "To your right side, you will find room A3.40", imageUrl: undefined },
  "363": { description: "To your right side, you will find room A3.38", imageUrl: undefined },
  "364": { description: "To your right side, you will find room A3.36", imageUrl: undefined },
  "365": { description: "To your right side, you will find room A3.34", imageUrl: undefined },
  "366": { description: "To your right side, you will find room A3.32", imageUrl: undefined },
  "367": { description: "To your left side, you will find room A3.41", imageUrl: undefined },
  "368": { description: "To your left side, you will find room A3.39", imageUrl: undefined },
  "369": { description: "To your left side, you will find room A3.37", imageUrl: undefined },
  "370": { description: "To your left side, you will find room A3.35", imageUrl: undefined },
  "371": { description: "To your left side, you will find room A3.33", imageUrl: undefined },
  "372": { description: "To your left side, you will find room A3.31", imageUrl: undefined },
  "373": { description: "To your right side, you will find room A3.43", imageUrl: undefined },
  "374": { description: "To your right side, you will find room A3.45", imageUrl: undefined },
  "375": { description: "To your right side, you will find room A3.47", imageUrl: undefined },
  "376": { description: "To your right side, you will find room A3.49", imageUrl: undefined },
  "377": { description: "To your right side, you will find room A3.51", imageUrl: undefined },
  "378": { description: "To your right side, you will find room A3.53", imageUrl: undefined },
  "379": { description: "To your right side, you will find room A3.55", imageUrl: undefined },
  "380": { description: "To your left side, you will find room A3.44", imageUrl: undefined },
  "381": { description: "To your left side, you will find room A3.46", imageUrl: undefined },
  "382": { description: "To your left side, you will find room A3.48", imageUrl: undefined },
  "383": { description: "To your left side, you will find room A3.50", imageUrl: undefined },
  "384": { description: "To your left side, you will find room A3.52", imageUrl: undefined },
  "385": { description: "To your left side, you will find room A3.54", imageUrl: undefined },
  "386": { description: "To your left side, you will find room A3.56", imageUrl: undefined },
  "387": { description: "Once you reach this floor, the center room you find will be A4.42.", imageUrl: undefined },
  "388": { description: "To your left side, you will find room A4.44", imageUrl: undefined },
  "389": { description: "To your left side, you will find room A4.46", imageUrl: undefined },
  "390": { description: "To your left side, you will find room A4.48", imageUrl: undefined },
  "391": { description: "To your left side, you will find room A4.50", imageUrl: undefined },
  "392": { description: "To your left side, you will find room A4.52", imageUrl: undefined },
  "393": { description: "To your left side, you will find room A4.54", imageUrl: undefined },
  "394": { description: "To your left side, you will find room A4.56", imageUrl: undefined },
  "395": { description: "To your right side, you will find room A4.40", imageUrl: undefined },
  "396": { description: "To your right side, you will find room A4.38", imageUrl: undefined },
  "397": { description: "To your right side, you will find room A4.36", imageUrl: undefined },
  "398": { description: "To your right side, you will find room A4.34", imageUrl: undefined },
  "399": { description: "To your right side, you will find room A4.32", imageUrl: undefined },
  "400": { description: "To your left side, you will find room A4.41", imageUrl: undefined },
  "401": { description: "To your left side, you will find room A4.39", imageUrl: undefined },
  "402": { description: "To your left side, you will find room A4.37", imageUrl: undefined },
  "403": { description: "To your left side, you will find room A4.35", imageUrl: undefined },
  "404": { description: "To your left side, you will find room A4.33", imageUrl: undefined },
  "405": { description: "To your left side, you will find room A4.31", imageUrl: undefined },
  "406": { description: "On the right side of this corridor, you will find room M001", imageUrl: undefined },
  "407": { description: "On the right side of this corridor, you will find room M002", imageUrl: undefined },
  "408": { description: "On the right side of this corridor, you will find room M003", imageUrl: undefined },
  "409": { description: "On the right side of this corridor, you will find room M004", imageUrl: undefined },
  "410": { description: "On the left side of this corridor, you will find room M008", imageUrl: undefined },
  "411": { description: "On the left side of this corridor, you will find room M007", imageUrl: undefined },
  "412": { description: "On the left side of this corridor, you will find room M006", imageUrl: undefined },
  "413": { description: "On the left side of this corridor, you will find room M005", imageUrl: undefined },
  "414": { description: "To your right, you will find room M009", imageUrl: undefined },
  "415": { description: "To your right, you will find room M010", imageUrl: undefined },
  "416": { description: "To your right, you will find room M011", imageUrl: undefined },
  "417": { description: "To your right, you will find room M012", imageUrl: undefined },
  "418": { description: "To your right, you will find room M013", imageUrl: undefined },
  "419": { description: "To your left, you will find room M018", imageUrl: undefined },
  "420": { description: "To your left, you will find room M017", imageUrl: undefined },
  "421": { description: "To your left, you will find room M016", imageUrl: undefined },
  "422": { description: "To your left, you will find room M015", imageUrl: undefined },
  "423": { description: "To your left, you will find room M014", imageUrl: undefined },
  "424": { description: "To your right, you will find room M029", imageUrl: undefined },
  "425": { description: "To your right, you will find room M030", imageUrl: undefined },
  "426": { description: "To your right, you will find room M031", imageUrl: undefined },
  "427": { description: "To your right, you will find room M032", imageUrl: undefined },
  "428": { description: "To your left, you will find room M036", imageUrl: undefined },
  "429": { description: "To your left, you will find room M035", imageUrl: undefined },
  "430": { description: "To your left, you will find room M034", imageUrl: undefined },
  "431": { description: "To your left, you will find room M033", imageUrl: undefined },
  "432": { description: "On the right side of this corridor, you will find room M101", imageUrl: undefined },
  "433": { description: "On the right side of this corridor, you will find room M102", imageUrl: undefined },
  "434": { description: "On the right side of this corridor, you will find room M103", imageUrl: undefined },
  "435": { description: "On the right side of this corridor, you will find room M104", imageUrl: undefined },
  "436": { description: "On the left side of this corridor, you will find room M108", imageUrl: undefined },
  "437": { description: "On the left side of this corridor, you will find room M107", imageUrl: undefined },
  "438": { description: "On the left side of this corridor, you will find room M106", imageUrl: undefined },
  "439": { description: "On the left side of this corridor, you will find room M105", imageUrl: undefined },
  "440": { description: "To your right, you will find room M109", imageUrl: undefined },
  "441": { description: "To your right, you will find room M110", imageUrl: undefined },
  "442": { description: "To your right, you will find room M111", imageUrl: undefined },
  "443": { description: "To your right, you will find room M112", imageUrl: undefined },
  "444": { description: "To your right, you will find room M113", imageUrl: undefined },
  "445": { description: "To your left, you will find room M118", imageUrl: undefined },
  "446": { description: "To your left, you will find room M117", imageUrl: undefined },
  "447": { description: "To your left, you will find room M116", imageUrl: undefined },
  "448": { description: "To your left, you will find room M115", imageUrl: undefined },
  "449": { description: "To your left, you will find room M114", imageUrl: undefined },
  "450": { description: "On the right side of this corridor, you will find room M119", imageUrl: undefined },
  "451": { description: "On the right side of this corridor, you will find room M120", imageUrl: undefined },
  "452": { description: "On the right side of this corridor, you will find room M121", imageUrl: undefined },
  "453": { description: "On the right side of this corridor, you will find room M122", imageUrl: undefined },
  "454": { description: "On the right side of this corridor, you will find room M123", imageUrl: undefined },
  "455": { description: "On the left side of this corridor, you will find room M128", imageUrl: undefined },
  "456": { description: "On the left side of this corridor, you will find room M127", imageUrl: undefined },
  "457": { description: "On the left side of this corridor, you will find room M126", imageUrl: undefined },
  "458": { description: "On the left side of this corridor, you will find room M125", imageUrl: undefined },
  "459": { description: "On the left side of this corridor, you will find room M124", imageUrl: undefined },
  "460": { description: "To your right, you will find room M129", imageUrl: undefined },
  "461": { description: "To your right, you will find room M130", imageUrl: undefined },
  "462": { description: "To your right, you will find room M131", imageUrl: undefined },
  "463": { description: "To your right, you will find room M132", imageUrl: undefined },
  "464": { description: "To your left, you will find room M136", imageUrl: undefined },
  "465": { description: "To your right, you will find room M135", imageUrl: undefined },
  "466": { description: "To your right, you will find room M134", imageUrl: undefined },
  "467": { description: "To your right, you will find room M133", imageUrl: undefined },
  "468": { description: "Look to your right side, you will find Classroom 2", imageUrl: undefined },
  "469": { description: "Look to your right side, you will find Classroom 4", imageUrl: undefined },
  "470": { description: "Look to your right side, you will find Classroom 6", imageUrl: undefined },
  "471": { description: "Look to your left side, you will find Classroom 1", imageUrl: undefined },
  "472": { description: "Look to your left side, you will find Classroom 3", imageUrl: undefined },
  "473": { description: "Look to your left side, you will find Classroom 5", imageUrl: undefined },
  "474": { description: "You will find room B1.06", imageUrl: undefined },
  "475": { description: "You will find room B1.05", imageUrl: undefined },
  "476": { description: "You will find room B1.04", imageUrl: undefined },
  "477": { description: "You will find room B1.03", imageUrl: undefined },
  "478": { description: "You will find room B1.02", imageUrl: undefined },
  "479": { description: "You will find room B1.01", imageUrl: undefined },
  "480": { description: "You will find room B2.39", imageUrl: undefined },
  "481": { description: "You will find room B1.08", imageUrl: undefined },
  "482": { description: "You will find room B1.09", imageUrl: undefined },
  "483": { description: "You will find room B1.10", imageUrl: undefined },
  "484": { description: "You will find room B1.11", imageUrl: undefined },
  "485": { description: "You will find room B1.12", imageUrl: undefined },
  "486": { description: "To your right side, you will find room B2.15", imageUrl: undefined },
  "487": { description: "To your right side, you will find room B2.13", imageUrl: undefined },
  "488": { description: "To your right side, you will find room B2.11", imageUrl: undefined },
  "489": { description: "To your right side, you will find room B2.0